version: '3.8'

services:
  # Database Service
  database-service:
    build: ./storage-node/database
    ports:
      - "3306:3306"
    networks:
      - music-network

  # Music Service
  music-service-node:
    build: ./music-service-node
    ports:
      - "8080:8080"
    networks:
      - music-network
    depends_on:
      - database-service
      - management-user-service
      - storage-service
      - logstash  # Phụ thuộc vào Logstash để gửi log

  # Management User Service
  management-user-service:
    build: ./management-node/management
    ports:
      - "8084:8084"
    networks:
      - music-network
    depends_on:
      - database-service
      - logstash  # Phụ thuộc vào Logstash để gửi log

  # Storage Service
  storage-service:
    build: ./storage-node/storage
    ports:
      - "8083:8083"
    volumes:
      - storage-data:/data
    networks:
      - music-network
    depends_on:
      - logstash  # Phụ thuộc vào Logstash để gửi log

  # ELK Stack
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - music-network

  logstash:
    image: logstash:7.17.9
    container_name: logstash
    volumes:
      - ./elk-stack/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    networks:
      - music-network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.17.9
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - music-network
    depends_on:
      - elasticsearch

networks:
  music-network:
    driver: bridge

volumes:
  storage-data: